/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSentRouteImport } from './routes/_authenticated/sent'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDraftsRouteImport } from './routes/_authenticated/drafts'
import { Route as AuthenticatedComposeRouteImport } from './routes/_authenticated/compose'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedAiSearchRouteImport } from './routes/_authenticated/ai-search'
import { Route as AuthenticatedMessageIdRouteImport } from './routes/_authenticated/message.$id'
import { Route as AuthenticatedCategorySlugRouteImport } from './routes/_authenticated/category.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSentRoute = AuthenticatedSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDraftsRoute = AuthenticatedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComposeRoute = AuthenticatedComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiSearchRoute = AuthenticatedAiSearchRouteImport.update({
  id: '/ai-search',
  path: '/ai-search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessageIdRoute = AuthenticatedMessageIdRouteImport.update({
  id: '/message/$id',
  path: '/message/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategorySlugRoute =
  AuthenticatedCategorySlugRouteImport.update({
    id: '/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-search': typeof AuthenticatedAiSearchRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/search': typeof AuthenticatedSearchRoute
  '/sent': typeof AuthenticatedSentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/category/$slug': typeof AuthenticatedCategorySlugRoute
  '/message/$id': typeof AuthenticatedMessageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-search': typeof AuthenticatedAiSearchRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/search': typeof AuthenticatedSearchRoute
  '/sent': typeof AuthenticatedSentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/category/$slug': typeof AuthenticatedCategorySlugRoute
  '/message/$id': typeof AuthenticatedMessageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-search': typeof AuthenticatedAiSearchRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/compose': typeof AuthenticatedComposeRoute
  '/_authenticated/drafts': typeof AuthenticatedDraftsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/sent': typeof AuthenticatedSentRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/_authenticated/category/$slug': typeof AuthenticatedCategorySlugRoute
  '/_authenticated/message/$id': typeof AuthenticatedMessageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-search'
    | '/archive'
    | '/compose'
    | '/drafts'
    | '/home'
    | '/inbox'
    | '/search'
    | '/sent'
    | '/settings'
    | '/trash'
    | '/category/$slug'
    | '/message/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-search'
    | '/archive'
    | '/compose'
    | '/drafts'
    | '/home'
    | '/inbox'
    | '/search'
    | '/sent'
    | '/settings'
    | '/trash'
    | '/category/$slug'
    | '/message/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-search'
    | '/_authenticated/archive'
    | '/_authenticated/compose'
    | '/_authenticated/drafts'
    | '/_authenticated/home'
    | '/_authenticated/inbox'
    | '/_authenticated/search'
    | '/_authenticated/sent'
    | '/_authenticated/settings'
    | '/_authenticated/trash'
    | '/_authenticated/category/$slug'
    | '/_authenticated/message/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sent': {
      id: '/_authenticated/sent'
      path: '/sent'
      fullPath: '/sent'
      preLoaderRoute: typeof AuthenticatedSentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts': {
      id: '/_authenticated/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthenticatedDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compose': {
      id: '/_authenticated/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AuthenticatedComposeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-search': {
      id: '/_authenticated/ai-search'
      path: '/ai-search'
      fullPath: '/ai-search'
      preLoaderRoute: typeof AuthenticatedAiSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/message/$id': {
      id: '/_authenticated/message/$id'
      path: '/message/$id'
      fullPath: '/message/$id'
      preLoaderRoute: typeof AuthenticatedMessageIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/category/$slug': {
      id: '/_authenticated/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof AuthenticatedCategorySlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiSearchRoute: typeof AuthenticatedAiSearchRoute
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedComposeRoute: typeof AuthenticatedComposeRoute
  AuthenticatedDraftsRoute: typeof AuthenticatedDraftsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSentRoute: typeof AuthenticatedSentRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedCategorySlugRoute: typeof AuthenticatedCategorySlugRoute
  AuthenticatedMessageIdRoute: typeof AuthenticatedMessageIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiSearchRoute: AuthenticatedAiSearchRoute,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedComposeRoute: AuthenticatedComposeRoute,
  AuthenticatedDraftsRoute: AuthenticatedDraftsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSentRoute: AuthenticatedSentRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedCategorySlugRoute: AuthenticatedCategorySlugRoute,
  AuthenticatedMessageIdRoute: AuthenticatedMessageIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
